name: CI
on:
  pull_request:
  push:

env:
  SCALA211: 2.11.12
  # define Java options for both official sbt and sbt-extras
  JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
  JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            java: 8
            jobtype: 1
          - os: ubuntu-latest
            java: 8
            jobtype: 2
          - os: ubuntu-latest
            java: 11
            jobtype: 1
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.${{ matrix.java }}"
    - name: Coursier cache
      uses: coursier/cache-action@v5
    - name: Build and test
      shell: bash
      run: |
        case ${{ matrix.jobtype }} in
          1)
            sbt scalafmtCheck test:scalafmtCheck scalafmtSbtCheck +scoptJS/test +scoptJVM/test
            ;;
          2)
            echo skip Scala Native test because MUnit is not available
            sudo apt-get update
            sudo apt install clang libunwind-dev libgc-dev libre2-dev
            sbt ++$SCALA211! scoptNative/compile
            # env SCALANATIVE_VERSION="0.4.0-M2" sbt ++$SCALA211! scoptNative/test
            ;;
          *)
            echo unknown jobtype
            exit 1
        esac
        rm -rf "$HOME/.ivy2/local"
        find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
        find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
        find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
        find $HOME/.sbt                              -name "*.lock"
